name: Frontend Snyk Security Scan

on:
  push:
    paths:
      - 'src/gurubase-frontend/**'
  pull_request:
    branches: [master]
    paths:
      - 'src/gurubase-frontend/**'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/gurubase-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
